<?php

/**
 * @file
 * Allows to alter existing site information form.
 */


/**
 * Implements hook_menu().
 * URL added here gives json reprentation of a particular node.
 */

function adminsitepage_menu() { 
	  $items['page_json/%/%node'] = array(
	    'page callback' => 'node_json_output',
	    'page arguments' => array(2),
	    'access arguments' => array('access content'),
	  );

	  return $items;
}

/**
 * Implements hook_form_alter().
 * customize site information form by adding extra fields.
 */

function adminsitepage_form_alter(&$form, $form_state, $form_id) {
	  if($form_id == "system_site_information_settings") {
		$form['txt_field_apikey'] = array(
		    '#type' => 'textfield',
		    '#title' => t('Site API Key'),
		    '#size' => 60,
		    '#maxlength' => 128,    
		    '#required' => TRUE,
		    '#default_value' => variable_get('siteapikey', 'No API Key yet'),
		);
		
		$form['actions']['submit']['#value'] = t('Update configuration');  

		$form['#submit'][] = 'adminsitepage_handler';
	  }
}


/**
 * Implements submit handler function.
 */

function adminsitepage_handler($form, &$form_state){
	variable_set('siteapikey', $form_state['values']['txt_field_apikey']);
	drupal_set_message("Site API Key has been saved with value ".$form_state['values']['txt_field_apikey']);
}



/**
 * Implements json data of a particular node and content type page.
 */

function node_json_output($node) {
	$apikey = variable_get('siteapikey');
	$page_type = $node->type;

	if(trim(arg(1)) == $apikey && $page_type == "page") {
		 drupal_json_output($node);
	}
	else {
		return drupal_access_denied();
	}
 
}
